<?php
$flash = $this->flashMessenger();

$sucesso = $flash->render('success');
$error = null;

if ($flash->getCurrentErrorMessages()) {
    $error = '<ul><li class="error">' . current($flash->getCurrentErrorMessages()) . '</li></ul>';
    $flash->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();
} else {
    $error = $flash->render('error');
}

$info = $flash->render();
?>

<?php if ($sucesso || $error || $info) : ?>
    <div class="container-alertas">
        <?php if ($sucesso) : ?>
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"><img src="<?=$this->basePath('/assets/img/ico/ico_close_msg.png')?>" alt=""/></span></button>
                <?php echo $sucesso; ?>
            </div>
        <?php endif;
        if ($info) : ?>

        <?php endif;
        if ($error) : ?>
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"><img src="<?=$this->basePath('/assets/img/ico/ico_close_msg.png')?>" alt=""/></span></button>
                <?php echo $error; ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
